FROM --platform=linux/amd64 golang:1.23.2 AS build
ENV CGO_ENABLED=0
ENV GOOS=linux

WORKDIR /go/src/github.com/bricks-cloud/bricksllm/
COPY . /go/src/github.com/bricks-cloud/bricksllm/
RUN go build -ldflags="-s -w" -o ./bin/bricksllm ./cmd/bricksllm/main.go

FROM --platform=linux/amd64 alpine:3.20
RUN apk --no-cache add ca-certificates
WORKDIR /usr/bin
COPY --from=build /go/src/github.com/bricks-cloud/bricksllm/bin /go/bin
COPY --from=build /go/src/github.com/bricks-cloud/bricksllm/docs /docs

# Build-time arguments for configuration
ARG POSTGRESQL_HOSTS=localhost
ARG POSTGRESQL_DB_NAME=
ARG POSTGRESQL_USERNAME=
ARG POSTGRESQL_PASSWORD=
ARG POSTGRESQL_SSL_MODE=disable
ARG POSTGRESQL_PORT=5432
ARG POSTGRESQL_READ_TIME_OUT=2m
ARG POSTGRESQL_WRITE_TIME_OUT=5s

ARG REDIS_HOSTS=localhost
ARG REDIS_PORT=6379
ARG REDIS_USERNAME=
ARG REDIS_PASSWORD=
ARG REDIS_READ_TIME_OUT=1s
ARG REDIS_WRITE_TIME_OUT=500ms

ARG IN_MEMORY_DB_UPDATE_INTERVAL=5s
ARG PROXY_TIMEOUT=600s
ARG NUMBER_OF_EVENT_MESSAGE_CONSUMERS=3
ARG CUSTOM_POLICY_DETECTION_TIMEOUT=10m
ARG REMOVE_USER_AGENT=false

ARG TELEMETRY_PROVIDER=statsd
ARG STATS_CONFIG_ENABLED=true
ARG STATS_CONFIG_ADDRESS=127.0.0.1:8125
ARG PROMETHEUS_ENABLED=false
ARG PROMETHEUS_PORT=2112

ARG AMAZON_REGION=us-west-2
ARG AMAZON_REQUEST_TIMEOUT=5s
ARG AMAZON_CONNECTION_TIMEOUT=10s

ARG OPENAI_API_KEY=
ARG ADMIN_PASS=
ARG CONFIG_FILE_NAME=

# Convert ARG to ENV variables
ENV POSTGRESQL_HOSTS=${POSTGRESQL_HOSTS}
ENV POSTGRESQL_DB_NAME=${POSTGRESQL_DB_NAME}
ENV POSTGRESQL_USERNAME=${POSTGRESQL_USERNAME}
ENV POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
ENV POSTGRESQL_SSL_MODE=${POSTGRESQL_SSL_MODE}
ENV POSTGRESQL_PORT=${POSTGRESQL_PORT}
ENV POSTGRESQL_READ_TIME_OUT=${POSTGRESQL_READ_TIME_OUT}
ENV POSTGRESQL_WRITE_TIME_OUT=${POSTGRESQL_WRITE_TIME_OUT}

ENV REDIS_HOSTS=${REDIS_HOSTS}
ENV REDIS_PORT=${REDIS_PORT}
ENV REDIS_USERNAME=${REDIS_USERNAME}
ENV REDIS_PASSWORD=${REDIS_PASSWORD}
ENV REDIS_READ_TIME_OUT=${REDIS_READ_TIME_OUT}
ENV REDIS_WRITE_TIME_OUT=${REDIS_WRITE_TIME_OUT}

ENV IN_MEMORY_DB_UPDATE_INTERVAL=${IN_MEMORY_DB_UPDATE_INTERVAL}
ENV PROXY_TIMEOUT=${PROXY_TIMEOUT}
ENV NUMBER_OF_EVENT_MESSAGE_CONSUMERS=${NUMBER_OF_EVENT_MESSAGE_CONSUMERS}
ENV CUSTOM_POLICY_DETECTION_TIMEOUT=${CUSTOM_POLICY_DETECTION_TIMEOUT}
ENV REMOVE_USER_AGENT=${REMOVE_USER_AGENT}

ENV TELEMETRY_PROVIDER=${TELEMETRY_PROVIDER}
ENV STATS_CONFIG_ENABLED=${STATS_CONFIG_ENABLED}
ENV STATS_CONFIG_ADDRESS=${STATS_CONFIG_ADDRESS}
ENV PROMETHEUS_ENABLED=${PROMETHEUS_ENABLED}
ENV PROMETHEUS_PORT=${PROMETHEUS_PORT}

ENV AMAZON_REGION=${AMAZON_REGION}
ENV AMAZON_REQUEST_TIMEOUT=${AMAZON_REQUEST_TIMEOUT}
ENV AMAZON_CONNECTION_TIMEOUT=${AMAZON_CONNECTION_TIMEOUT}

ENV OPENAI_API_KEY=${OPENAI_API_KEY}
ENV ADMIN_PASS=${ADMIN_PASS}
ENV CONFIG_FILE_NAME=${CONFIG_FILE_NAME}

EXPOSE 8001 8002
ENTRYPOINT ["/go/bin/bricksllm"]

CMD ["-m", "production"]